# Generated by Django 3.2 on 2023-04-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
